name: ci
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init --recursive || true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt pytest
      - run: PYTHONPATH=src pytest -q
      - run: PYTHONPATH=src python -c "from datalake.config import LakeConfig; print(LakeConfig())"
      - run: PYTHONPATH=src python src/datalake/validate_layout.py || true
